services:
  web:
    build: .
    container_name: flask_app
    environment:
      - FLASK_ENV=development
      - DEBUG=True
    ports:
      - "5000:5000"
    restart: always
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    deploy:
      resources:
        limits:
          memory: "256m"
          cpus: "0.50"